/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIFloatBallSettings: typeof import('./src/components/Settings/AIFloatBallSettings.vue')['default']
    AudioVisualizer: typeof import('./src/components/Play/AudioVisualizer.vue')['default']
    DirectorySettings: typeof import('./src/components/Settings/DirectorySettings.vue')['default']
    FloatBall: typeof import('./src/components/AI/FloatBall.vue')['default']
    FullPlay: typeof import('./src/components/Play/FullPlay.vue')['default']
    GlobalAudio: typeof import('./src/components/Play/GlobalAudio.vue')['default']
    HomeLayout: typeof import('./src/components/layout/HomeLayout.vue')['default']
    MusicCache: typeof import('./src/components/Settings/MusicCache.vue')['default']
    PlaylistActions: typeof import('./src/components/Play/PlaylistActions.vue')['default']
    PlaylistDrawer: typeof import('./src/components/Play/PlaylistDrawer.vue')['default']
    PlaylistSettings: typeof import('./src/components/Settings/PlaylistSettings.vue')['default']
    PlayMusic: typeof import('./src/components/Play/PlayMusic.vue')['default']
    PluginNoticeDialog: typeof import('./src/components/PluginNoticeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShaderBackground: typeof import('./src/components/Play/ShaderBackground.vue')['default']
    SongVirtualList: typeof import('./src/components/Music/SongVirtualList.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    ThemeSelector: typeof import('./src/components/ThemeSelector.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TitleBarControls: typeof import('./src/components/TitleBarControls.vue')['default']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    UpdateExample: typeof import('./src/components/UpdateExample.vue')['default']
    UpdateProgress: typeof import('./src/components/UpdateProgress.vue')['default']
    UpdateSettings: typeof import('./src/components/Settings/UpdateSettings.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
