/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIFloatBallSettings: typeof import('./src/components/Settings/AIFloatBallSettings.vue')['default']
    AudioVisualizer: typeof import('./src/components/Play/AudioVisualizer.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/ContextMenu.vue')['default']
    Demo: typeof import('./src/components/ContextMenu/demo.vue')['default']
    DirectorySettings: typeof import('./src/components/Settings/DirectorySettings.vue')['default']
    FloatBall: typeof import('./src/components/AI/FloatBall.vue')['default']
    FullPlay: typeof import('./src/components/Play/FullPlay.vue')['default']
    GlobalAudio: typeof import('./src/components/Play/GlobalAudio.vue')['default']
    HomeLayout: typeof import('./src/components/layout/HomeLayout.vue')['default']
    MusicCache: typeof import('./src/components/Settings/MusicCache.vue')['default']
    PlaylistActions: typeof import('./src/components/Play/PlaylistActions.vue')['default']
    PlaylistDrawer: typeof import('./src/components/Play/PlaylistDrawer.vue')['default']
    PlaylistSettings: typeof import('./src/components/Settings/PlaylistSettings.vue')['default']
    PlayMusic: typeof import('./src/components/Play/PlayMusic.vue')['default']
    PluginNoticeDialog: typeof import('./src/components/PluginNoticeDialog.vue')['default']
    Plugins: typeof import('./src/components/Settings/plugins.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShaderBackground: typeof import('./src/components/Play/ShaderBackground.vue')['default']
    SongVirtualList: typeof import('./src/components/Music/SongVirtualList.vue')['default']
    ThemeSelector: typeof import('./src/components/ThemeSelector.vue')['default']
    TitleBarControls: typeof import('./src/components/TitleBarControls.vue')['default']
    UpdateExample: typeof import('./src/components/UpdateExample.vue')['default']
    UpdateProgress: typeof import('./src/components/UpdateProgress.vue')['default']
    UpdateSettings: typeof import('./src/components/Settings/UpdateSettings.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
